USE SCHOOL3;
CREATE TABLE PRO_2
(
 BA_ID INT unsigned,
 BA_NAME varchar(55),
 BA_ADDRESS TEXT,
 BA_GENDER ENUM("M","F"),
 BA_DOB DATE,
 primary key (BA_ID)
);
SELECT * from PRO_2;
SELECT BA_NAME,BA_ID,BA_ADDRESS FROM PRO_2;